using System;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEngine;
using YanickSenn.Utils.Variables;

namespace YanickSenn.Utils.Editor.Variables {

    public static class VariableGenerator {

        [DidReloadScripts]
        public static void OnScriptsReloaded() {
             Generate();
        }

        [MenuItem("Tools/YanickSenn/Utils/Force Generate Variables")]
        public static void Generate() {
            if (UtilsSettings.instance.VariableGenerationSettings.disabled) {
                return;
            }

            var targetTypes = TypeCache.GetTypesWithAttribute<GenerateVariableAttribute>();
            var outputDir = "Assets/Generated/Variables";

            if (!Directory.Exists(outputDir)) {
                Directory.CreateDirectory(outputDir);
            }

            foreach (var type in targetTypes) {
                var attr = System.Reflection.CustomAttributeExtensions.GetCustomAttribute<GenerateVariableAttribute>(type);
                if (attr != null && attr.Generate) {
                    GenerateVariableForType(type, outputDir);
                    GenerateReferenceForType(type, outputDir);
                }
            }
            
            AssetDatabase.Refresh();
        }

        private static void GenerateVariableForType(Type type, string outputDir) {
            var className = $"{type.Name}Variable";
            var filePath = Path.Combine(outputDir, $"{className}.cs");
            var typeFullName = type.FullName.Replace('+', '.');

            var sb = new StringBuilder();
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using YanickSenn.Utils;");
            sb.AppendLine("using YanickSenn.Utils.Variables;");
            sb.AppendLine();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     This code was generated by YanickSenn.Utils.Editor.Variables.VariableGenerator.");
            sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
            sb.AppendLine("//     the code is regenerated.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("namespace YanickSenn.Generated.Variables {");
            sb.AppendLine();
            var menuName = ObjectNames.NicifyVariableName(className);
            sb.AppendLine($"    [Generated]");
            sb.AppendLine($"    [CreateAssetMenu(fileName = \"{className}\", menuName = \"Variables/{menuName}\")]");
            sb.AppendLine($"    public class {className} : Variable<{typeFullName}> {{ }}");
            sb.AppendLine("}");

            var content = sb.ToString();
            if (!File.Exists(filePath) || File.ReadAllText(filePath) != content) {
                File.WriteAllText(filePath, content);
                Debug.Log($"Generated variable: {filePath}");
            }
        }

        private static void GenerateReferenceForType(Type type, string outputDir) {
            var variableClassName = $"{type.Name}Variable";
            var className = $"{type.Name}Reference";
            var filePath = Path.Combine(outputDir, $"{className}.cs");
            var typeFullName = type.FullName.Replace('+', '.');

            var sb = new StringBuilder();
            sb.AppendLine("using System;");
            sb.AppendLine("using YanickSenn.Utils;");
            sb.AppendLine("using YanickSenn.Utils.Variables;");
            sb.AppendLine();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     This code was generated by YanickSenn.Utils.Editor.Variables.VariableGenerator.");
            sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
            sb.AppendLine("//     the code is regenerated.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("namespace YanickSenn.Generated.Variables {");
            sb.AppendLine();
            sb.AppendLine("    [Generated]");
            sb.AppendLine("    [Serializable]");
            sb.AppendLine($"    public class {className} : Reference<{typeFullName}, {variableClassName}> {{");
            sb.AppendLine($"        public {className}({typeFullName} value = default) : base(value) {{ }}");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            var content = sb.ToString();
            if (!File.Exists(filePath) || File.ReadAllText(filePath) != content) {
                File.WriteAllText(filePath, content);
                Debug.Log($"Generated reference: {filePath}");
            }
        }
    }
}